apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-app.yaml
- pacman-ci.yaml
- pacman-ci-production.yaml
- env/pacman-cd-development.yaml
- env/pacman-cd-qa.yaml
- env/pacman-cd-production.yaml
- pacman-project.yaml
- baseimage.yaml
